### ISSUE TITLE
Map not displaying properly

### ISSUE THREAD

**Issue by vrabaud** [DLu/ros_map#82]
Not sure what happened but only white dots appear for me:
http://metrorobots.com/rosmap.html

**Comment by DLu** [comment]
This is a [wider issue](https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=kmllayer&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=8551) than just ROS Map that has just started popping up recently. If the problem is not fixed soonish, I'll hack around it.

**Comment by DLu** [comment]
Annoyingly, you can get the color to display if its using a google.com image. Fixed for a bit, unless this breaks again.
